apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: sec-volume
          readOnly: true
          mountPath: /etc/secret
      ports:
        - name: web
          containerPort: 80
          protocol: TCP

  volumes:
    - name: sec-volume
      secret:
        secretName: domain-cert
