apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
    - name: multitool
      image: praqma/network-multitool:apline-extra
      imagePullPolicy: ifNotPresent
      ports:
        - containerPort: 80
          name: web
#  volumes:
#    - name: secret-vol
#      secret:
#        secretName:


